### ISSUE TITLE
Check error messsage on decoding the wrong type from a config

### ISSUE THREAD

**Issue by bbkane** [bbkane/warg#40]
For example, when I expect an int and there's a string in the config. That should really have a good error message...

**Comment by bbkane** [comment]
Example:

```yaml
# make lumberjacklogger nil to not log to file
lumberjacklogger:
  filename: ~/.config/grabbit.jsonl
  maxsize: 5  # megabytes
  maxbackups: 0
  maxage: 30  # days
destination: ~/Pictures/grabbit
subreddits:
  - name: architectureporn
    timeframe: "week"
    count: "TWO this is bad"
  - name: churchporn
    timeframe: "week"
    count: 1
  - name: cityporn
    timeframe: "week"
    count: 4
  - name: earthporn
    timeframe: "week"
    count: 10
  - name: futureporn
    timeframe: "week"
    count: 1
  - name: imaginarycastles
    timeframe: "week"
    count: 3
  - name: villageporn
    timeframe: "week"
    count: 2
  - name: roomporn
    timeframe: "week"
    count: 1
  - name: wallpapers
    timeframe: "week"
    count: 2
version: v5
```

```
$ grabbit grab -h
ResolveFlag error for command flag --subreddit-info

could not replace container type value:
val:
&slice.sliceValue[main.SubredditInfo]{choices:[]main.SubredditInfo{}, defaultVals:[]main.SubredditInfo{main.SubredditInfo{Subreddit:"earthporn", Timeframe:"week", Count:2}}, hasDefault:true, inner:contained.TypeInfo[main.SubredditInfo]{Description:"SubredditInfo represents a subreddit, timeframe, and count", FromIFace:(func(interface {}) (main.SubredditInfo, error))(0x102f43910), FromString:(func(string) (main.SubredditInfo, error))(0x102f436c0), FromZero:(func() main.SubredditInfo)(0x102f44840), Equals:(func(main.SubredditInfo, main.SubredditInfo) bool)(0x102f44770)}, vals:[]main.SubredditInfo(nil), updatedBy:""}
replacement:
[]interface {}{map[string]interface {}{"count":"TWO this is bad", "name":"architectureporn", "timeframe":"week"}, map[string]interface {}{"count":0x1, "name":"churchporn", "timeframe":"week"}, map[string]interface {}{"count":0x4, "name":"cityporn", "timeframe":"week"}, map[string]interface {}{"count":0xa, "name":"earthporn", "timeframe":"week"}, map[string]interface {}{"count":0x1, "name":"futureporn", "timeframe":"week"}, map[string]interface {}{"count":0x3, "name":"imaginarycastles", "timeframe":"week"}, map[string]interface {}{"count":0x2, "name":"villageporn", "timeframe":"week"}, map[string]interface {}{"count":0x1, "name":"roomporn", "timeframe":"week"}, map[string]interface {}{"count":0x2, "name":"wallpapers", "timeframe":"week"}}

expected count to be uint64, got string
```
